// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHYeioQG2hkPnf1Egud7OQqAPs5uCTZw',
    appId: '1:794451457797:web:b42958351dbf4871be696c',
    messagingSenderId: '794451457797',
    projectId: 'trydiaryco',
    authDomain: 'trydiaryco.firebaseapp.com',
    storageBucket: 'trydiaryco.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjkSJ1nb5SjHbh27vEEgCYwyc8bVGWpA',
    appId: '1:794451457797:android:99fbfd427abb3516be696c',
    messagingSenderId: '794451457797',
    projectId: 'trydiaryco',
    storageBucket: 'trydiaryco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0I64PQCziSTjET8U_Mxm-gFNjRKxrCCk',
    appId: '1:794451457797:ios:d8c172adbdb48cbcbe696c',
    messagingSenderId: '794451457797',
    projectId: 'trydiaryco',
    storageBucket: 'trydiaryco.appspot.com',
    iosBundleId: 'com.example.loginUi2023',
  );
}
